<a href="https://colab.research.google.com/github/vinodsharma19/PythonBootcamp/blob/main/Copy_of_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# list
# tuples
# sets
# dict
# strings
# if elif else
# def | lambda
# for while

In [ ]:

# NumPy -> Numerical Python!
# array -> fast, multidimensional objects used for numerical calcualtions!

In [ ]:
import numpy  as np
import pandas as pd

In [ ]:
arr_1d = np.array([1,2,3,4,5])
arr_1d

array([1, 2, 3, 4, 5])

In [ ]:
print(arr_1d)

[1 2 3 4 5]


In [ ]:
arr_1d = np.array((1,2,3,4,5))
arr_1d

array([1, 2, 3, 4, 5])

In [ ]:
type(arr_1d)

numpy.ndarray

In [ ]:
arr_1d.ndim #dimension of the array!

1

In [ ]:
# 2d array :
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr_2d.ndim

2

In [ ]:
arr_2d.shape #rows,columns!

(2, 3)

In [ ]:
# zero!
arr_zero = np.zeros(5)
arr_zero

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
# np.ones
arr_1 = np.ones(10)
arr_1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
# Creating two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

In [ ]:
arr1 + arr2 #addition!

array([ 6,  8, 10, 12])

In [ ]:
arr1 - arr2 #sub

array([-4, -4, -4, -4])

In [ ]:
arr1*arr2

array([ 5, 12, 21, 32])

In [ ]:
arr1/arr2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [ ]:
arr = np.array([5,10,15,20,25])
arr

array([ 5, 10, 15, 20, 25])

In [ ]:
np.min(arr)

np.int64(5)

In [ ]:
np.max(arr)

np.int64(25)

In [ ]:
np.mean(arr)

np.float64(15.0)

In [ ]:
np.median(arr)

np.float64(15.0)

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# no. of elemets - 12 | as of now its 1d array
# reshape array to other shapes , which other shapes are applicable?
# 2x6 | 6x2 | 3x4 | 4x3 | 12*1 | 1*12 - CAN
# 1x8 , 10x1 - CANNOT (Total elements - 12)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr.reshape(3,4) #error

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
arr = np.array([5,12,1,0,3])
arr

array([ 5, 12,  1,  0,  3])

In [ ]:
arr[0]

np.int64(5)

In [ ]:
arr[3] # 3rd index ; 4th element

np.int64(0)

In [ ]:
# what is an identity matrix?

In [ ]:
# nxn array diagnol with 1 as diagnol

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])